import Head from 'next/head'
import { useState, useRef, useEffect } from 'react';
// import { Inter } from 'next/font/google'
import { trpc } from '../utils/trpc';
// import styles from '@/styles/Home.module.css'

// const inter = Inter({ subsets: ['latin'] })

export default function IndexPage() {
  const [username, setUsername] = useState('');
  const [users, setUsers] = useState(null);
  const inputRef = useRef(null);
  const hello = trpc.hello.useQuery({ text: 'Murashama' });
  const allUsers = trpc.allUsers.useQuery();
  const getUser = trpc.userById.useQuery("1");
  const sendUser = trpc.userCreate.useMutation();

  useEffect(() => {
    setUsers(allUsers?.data)
  }, [allUsers?.data]);

  if (!hello.data) {
    return <div>Loading...</div>;
  }

  const handleName = (event) => {
    // console.log(event.target.value);
    setUsername(event.target.value);
  }
  // console.log(getUser.data);
  const handleMutation = () => {
    //  console.log(sendUser);
     if (username && username.trim().length > 0) {
      const id = Date.now()
      sendUser.mutate({name: username})
      // console.log(sendUser);
      setUsername('');
      inputRef.current.value = ''
      // console.log(allUsers);
      const newUser = {id, name: username}
      setUsers([...users, newUser])
     }
     
  }
  // console.log(allUsers);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Hola</h1>
        <p>{hello.data.greeting}</p>
        <h2>We are trying to reach...</h2>
        <p>{getUser.data?.name}</p>

        <input ref={inputRef} type="text" onChange={handleName} name="username" placeholder='write your name' />
        <button type="submit" onClick={handleMutation}>Enviar</button>
        <p>{sendUser?.data?.name}</p>
        <ul>
          {users?.map((user, index) => (
            <li key={index}>{user.name}</li>
          ))}
        </ul>
      </main>
    </>
  )
}
